name: 同步代码到gitee和CNB
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GIT_USER: ${{ secrets.GITEE_USER }}
      GIT_EMAIL: ${{ secrets.GITEE_EMAIL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Accept Gitee Host Key
        run: |
          echo -e "Host gitee.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Configure Git User
        run: |
          git config --global user.name "${{ secrets.GITEE_USER }}"
          git config --global user.email "${{ secrets.GITEE_EMAIL }}"

      - name: Add Gitee Remote
        run: git remote add gitee git@gitee.com:qinjielove/mzapi-ts.git

      - name: Push to Gitee
        run: git push gitee main

  sync-to-cnb:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GIT_USER: ${{ secrets.CNB_USER }}
      GIT_EMAIL: ${{ secrets.CNB_EMAIL }}
      CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure Git User
        run: |
          git config --global user.name "${{ secrets.GIT_USER }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Add CNB Remote
        run: git remote add cnb https://${{ secrets.CNB_TOKEN }}@cnb.cool/XMZZUZHI/MZAPI/TypeScript.git

      - name: Push to CNB
        run: git push cnb main